#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"

bash "$ROOT/Tests/Collector/run-release-tests.sh"
python3 "$ROOT/Tests/Release/test_release_package.py"
python3 "$ROOT/Tests/Release/test_release_hygiene.py"
python3 "$ROOT/Tests/Release/test_demo_static.py"
python3 "$ROOT/Tests/Release/test_demo_browser.py"
python3 "$ROOT/Tests/Release/test_projection.py"
python3 "$ROOT/Tests/Release/test_sample_route.py"
python3 "$ROOT/Tests/Release/test_map_pixels.py"
python3 "$ROOT/Tests/Release/test_scenario_catalog.py"
python3 "$ROOT/Tests/Release/test_scenario_browser.py"
python3 "$ROOT/Tests/Release/test_visual_assets.py"
python3 "$ROOT/Tests/Release/test_performance_fidelity.py"
python3 "$ROOT/Tests/Release/test_native_assets.py"
python3 "$ROOT/Tests/Release/test_replay_matrix.py"
node "$ROOT/Tests/Release/site_renderer_coherence.js"
node "$ROOT/Tests/Release/native_map_adapter.js"
node --check "$ROOT/Web/outdoor-map-projection.js"
node --check "$ROOT/Web/replay-renderer.js"
node --check "$ROOT/Web/map-native-adapter.js"
echo "all tests passed"
